#! /bin/bash

# Set working directory in /tmp. This can be changed.
mkdir -p /tmp/radar
cd /tmp/radar

# Set icon for notification. This can also be changed.
icon="./logo-kmi--nl.png"

# Download images
notify-send -i ${icon} "Buienradar" "Downloading images..."
for ((i=0;i<=90;i+=5)); do
    newtime=$(echo "$(date --date="${i} minutes ago" +%H%M) - ($(date +%M)%5)" | bc )
    if (("${newtime}"<"1000")); then
        newtime="0${newtime}"
    fi
    date=$(date --date="${i} minutes ago" +%Y%m%d)
    num="${date}_${newtime}00"
    wget https://www.meteo.be/media/cache/meteostore_background_jpg/images/RadCompBNLX/NL/belRadComp${num}.jpg
done

# Convert images to GIF
notify-send -i ${icon} "Buienradar" "Processing images..."
convert -delay 100 -loop 0 *.jpg ${num}.gif
rm *.jpg
curl v2d.wttr.in
mpv --loop-file=inf ${num}.gif
rm ${num}.gif
