#! /bin/bash

cd /home/simon/Buienradar

# Download images
for ((i=0;i<=90;i+=5)); do
    newtime=$(echo "$(date --date="${i} minutes ago" +%H%M) - ($(date +%M)%5)" | bc )
    if (("${newtime}"<"1000")); then
        newtime="0${newtime}"
    fi
    date=$(date --date="${i} minutes ago" +%Y%m%d)
    num="${date}_${newtime}00"
    wget https://www.meteo.be/media/cache/meteostore_background_jpg/images/RadCompBNLX/NL/belRadComp${num}.jpg
done

convert -delay 100 -loop 0 *.jpg ${num}.gif
rm *.jpg
mpv --loop-file= INF ${num}.gif
rm ${num}.gif
